version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    healthcheck: # https://github.com/Azure/Azurite/issues/1666#issue-1361671796
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    profiles:
      - local-dev
      - dev-containers
